@echo off
title Unity Project Setup
color 0A

echo ============================================
echo       UNITY PROJECT FOLDER STRUCTURE
echo ============================================
echo.

:: ─── INPUT NAMA PROJECT ───────────────────────
set /p ProjectName=Masukkan nama project: 

if "%ProjectName%"=="" (
    echo [ERROR] Nama project tidak boleh kosong!
    pause
    exit /b
)

echo.
echo [INFO] Membuat struktur folder untuk: %ProjectName%
echo.

:: ─── BUAT ROOT FOLDER ─────────────────────────
mkdir "%ProjectName%"
mkdir "%ProjectName%\Assets"

:: ─── ASSETS SUB FOLDER ────────────────────────
mkdir "%ProjectName%\Assets\Animations"
mkdir "%ProjectName%\Assets\Audio"
mkdir "%ProjectName%\Assets\Audio\Music"
mkdir "%ProjectName%\Assets\Audio\SFX"
mkdir "%ProjectName%\Assets\Editor"
mkdir "%ProjectName%\Assets\Fonts"
mkdir "%ProjectName%\Assets\Materials"
mkdir "%ProjectName%\Assets\Models"
mkdir "%ProjectName%\Assets\Plugins"
mkdir "%ProjectName%\Assets\Prefabs"
mkdir "%ProjectName%\Assets\Resources"
mkdir "%ProjectName%\Assets\Scenes"
mkdir "%ProjectName%\Assets\Scripts"
mkdir "%ProjectName%\Assets\Scripts\Controllers"
mkdir "%ProjectName%\Assets\Scripts\Managers"
mkdir "%ProjectName%\Assets\Scripts\Models"
mkdir "%ProjectName%\Assets\Scripts\UI"
mkdir "%ProjectName%\Assets\Shaders"
mkdir "%ProjectName%\Assets\Sprites"
mkdir "%ProjectName%\Assets\Textures"
mkdir "%ProjectName%\Assets\UI"
mkdir "%ProjectName%\Assets\StreamingAssets"

:: ─── PACKAGES & SETTINGS ──────────────────────
mkdir "%ProjectName%\Packages"
mkdir "%ProjectName%\ProjectSettings"
mkdir "%ProjectName%\UserSettings"

:: ─── BUAT .gitignore ──────────────────────────
echo [INFO] Membuat .gitignore...

(
echo # =============================================
echo # Unity .gitignore
echo # =============================================
echo.
echo # ----- Folder yang di-generate otomatis -----
echo [Ll]ibrary/
echo [Tt]emp/
echo [Oo]bj/
echo [Bb]uild/
echo [Bb]uilds/
echo [Ll]ogs/
echo [Uu]ser[Ss]ettings/
echo.
echo # ----- MemoryCaptures -----
echo [Mm]emoryCaptures/
echo.
echo # ----- Asset meta data -----
echo !/[Aa]ssets/**/*.meta
echo.
echo # ----- Crash reportings -----
echo sysinfo.txt
echo.
echo # ----- Cache -----
echo *.pidb.meta
echo *.pdb.meta
echo *.mdb.meta
echo.
echo # ----- Unity3D generated file on crash reports -----
echo crashlytics-build.properties
echo.
echo # ----- Autogenerated VS/MD/Consulo solution and project files -----
echo ExportedObj/
echo .consulo/
echo *.csproj
echo *.unityproj
echo *.sln
echo *.suo
echo *.tmp
echo *.user
echo *.userprefs
echo *.pidb
echo *.booproj
echo *.svd
echo *.pdb
echo *.mdb
echo *.opendb
echo *.VC.db
echo.
echo # ----- Unity3D generated meta files -----
echo *.pidb.meta
echo *.pdb.meta
echo *.mdb.meta
echo.
echo # ----- OS generated files -----
echo .DS_Store
echo .DS_Store?
echo ._*
echo .Spotlight-V100
echo .Trashes
echo ehthumbs.db
echo Thumbs.db
echo Desktop.ini
echo.
echo # ----- JetBrains Rider -----
echo .idea/
echo *.sln.iml
echo.
echo # ----- Visual Studio -----
echo .vs/
echo.
echo # ----- Visual Studio Code -----
echo .vscode/
echo.
echo # ----- Gradle -----
echo .gradle/
echo.
echo # =============================================
echo # Yang WAJIB di-commit:
echo # Assets/
echo # Packages/
echo # ProjectSettings/
echo # =============================================
) > "%ProjectName%\.gitignore"

:: ─── BUAT README.md ────────────────────────────
(
echo # %ProjectName%
echo.
echo Unity Project — dibuat dengan Setup_Unity_Project.bat
echo.
echo ## Struktur Folder
echo.
echo ```
echo Assets/
echo ├── Animations/
echo ├── Audio/
echo │   ├── Music/
echo │   └── SFX/
echo ├── Editor/
echo ├── Fonts/
echo ├── Materials/
echo ├── Models/
echo ├── Plugins/
echo ├── Prefabs/
echo ├── Resources/
echo ├── Scenes/
echo ├── Scripts/
echo │   ├── Controllers/
echo │   ├── Managers/
echo │   ├── Models/
echo │   └── UI/
echo ├── Shaders/
echo ├── Sprites/
echo ├── StreamingAssets/
echo ├── Textures/
echo └── UI/
echo ```
) > "%ProjectName%\README.md"

:: ─── SELESAI ───────────────────────────────────
echo.
echo ============================================
echo   BERHASIL! Folder sudah dibuat:
echo.
echo   [OK] Assets ^& semua sub folder
echo   [OK] Packages/
echo   [OK] ProjectSettings/
echo   [OK] UserSettings/
echo   [OK] .gitignore (Unity)
echo   [OK] README.md
echo ============================================
echo.
echo Lokasi: %CD%\%ProjectName%
echo.

:: Buka folder hasil di Explorer
explorer "%ProjectName%"

pause
